[build-system]
requires = [
	"setuptools >= 65",
	"wheel >= 0.38",
]
build-backend = "setuptools.build_meta"


[tool.setuptools]
packages = ["hakuin", "hakuin.dbms", "hakuin.utils"]


[tool.setuptools.package-data]
hakuin = ["data/models/*.pkl"]


[project]
name = "hakuin"
version = "0.1.0"
requires-python = ">=3"
dependencies = [
	"nltk",
]
